server.port=8080

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preferQueryMode=simple
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=240000
spring.datasource.hikari.connection-test-query=SELECT 1

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=default

# Apify Configuration
apify.token=${MY_APIFY_TOKEN}

# Gemini AI Configuration
gemini.api.key=${GEMINI_API_KEY}

# Security / JWT
jwt.secret=${MY_SECRET_KEY}
jwt.expiration=${MY_EXPIRATION_TIME}

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# GraphQL & System Settings
server.forward-headers-strategy=framework
spring.graphql.graphiql.enabled=true
spring.graphql.schema.printer.enabled=true

